//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ExplorateurImages
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet Entities à l'aide de la chaîne de connexion trouvée dans la section 'Entities' du fichier de configuration d'application.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Entities.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<SysBasisImage> SysBasisImage
        {
            get
            {
                if ((_SysBasisImage == null))
                {
                    _SysBasisImage = base.CreateObjectSet<SysBasisImage>("SysBasisImage");
                }
                return _SysBasisImage;
            }
        }
        private ObjectSet<SysBasisImage> _SysBasisImage;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet SysBasisImage. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSysBasisImage(SysBasisImage sysBasisImage)
        {
            base.AddObject("SysBasisImage", sysBasisImage);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContextModel", Name="SysBasisImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysBasisImage : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet SysBasisImage.
        /// </summary>
        /// <param name="imageNum">Valeur initiale de la propriété ImageNum.</param>
        /// <param name="imageId">Valeur initiale de la propriété ImageId.</param>
        /// <param name="imageCategoryId">Valeur initiale de la propriété ImageCategoryId.</param>
        /// <param name="width">Valeur initiale de la propriété Width.</param>
        /// <param name="height">Valeur initiale de la propriété Height.</param>
        /// <param name="fileName">Valeur initiale de la propriété FileName.</param>
        /// <param name="inFile">Valeur initiale de la propriété InFile.</param>
        public static SysBasisImage CreateSysBasisImage(global::System.Int32 imageNum, global::System.String imageId, global::System.String imageCategoryId, global::System.Int32 width, global::System.Int32 height, global::System.String fileName, global::System.Int16 inFile)
        {
            SysBasisImage sysBasisImage = new SysBasisImage();
            sysBasisImage.ImageNum = imageNum;
            sysBasisImage.ImageId = imageId;
            sysBasisImage.ImageCategoryId = imageCategoryId;
            sysBasisImage.Width = width;
            sysBasisImage.Height = height;
            sysBasisImage.FileName = fileName;
            sysBasisImage.InFile = inFile;
            return sysBasisImage;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageNum
        {
            get
            {
                return _ImageNum;
            }
            set
            {
                if (_ImageNum != value)
                {
                    OnImageNumChanging(value);
                    ReportPropertyChanging("ImageNum");
                    _ImageNum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageNum");
                    OnImageNumChanged();
                }
            }
        }
        private global::System.Int32 _ImageNum;
        partial void OnImageNumChanging(global::System.Int32 value);
        partial void OnImageNumChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                OnImageIdChanging(value);
                ReportPropertyChanging("ImageId");
                _ImageId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageId");
                OnImageIdChanged();
            }
        }
        private global::System.String _ImageId;
        partial void OnImageIdChanging(global::System.String value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageCategoryId
        {
            get
            {
                return _ImageCategoryId;
            }
            set
            {
                OnImageCategoryIdChanging(value);
                ReportPropertyChanging("ImageCategoryId");
                _ImageCategoryId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageCategoryId");
                OnImageCategoryIdChanged();
            }
        }
        private global::System.String _ImageCategoryId;
        partial void OnImageCategoryIdChanging(global::System.String value);
        partial void OnImageCategoryIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 InFile
        {
            get
            {
                return _InFile;
            }
            set
            {
                OnInFileChanging(value);
                ReportPropertyChanging("InFile");
                _InFile = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InFile");
                OnInFileChanged();
            }
        }
        private global::System.Int16 _InFile;
        partial void OnInFileChanging(global::System.Int16 value);
        partial void OnInFileChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String md5
        {
            get
            {
                return _md5;
            }
            set
            {
                Onmd5Changing(value);
                ReportPropertyChanging("md5");
                _md5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("md5");
                Onmd5Changed();
            }
        }
        private global::System.String _md5;
        partial void Onmd5Changing(global::System.String value);
        partial void Onmd5Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] DataImg
        {
            get
            {
                return StructuralObject.GetValidValue(_DataImg);
            }
            set
            {
                OnDataImgChanging(value);
                ReportPropertyChanging("DataImg");
                _DataImg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataImg");
                OnDataImgChanged();
            }
        }
        private global::System.Byte[] _DataImg;
        partial void OnDataImgChanging(global::System.Byte[] value);
        partial void OnDataImgChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();

        #endregion

    
    }

    #endregion

    
}
